### ISSUE TITLE
not detecting probe on raspberry pi

### ISSUE THREAD

**Issue by dizzybro** [legrego/homeassistant-combustion#33]
Hello,
I Installed your addon per the directions, and the integration shows up on my list, but no devices are being detected. I'm running HASSOS on a Raspberry Pi 4.

**Comment by dizzybro** [comment]
Nevermind, it took about 10 minutes to detect it initially, but working now!

**Comment by legrego** [comment]
Glad you got it working! I'll close this for now, but feel free to start a new issue if you encounter other problems.
